// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SeedsBank.Server.Data;

#nullable disable

namespace SeedsBank.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260718192150_AddFields")]
    partial class AddFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SeedsBank.Server.Models.Field", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<double>("LandLength")
                        .HasColumnType("double")
                        .HasColumnName("land_length");

                    b.Property<double>("LandWidth")
                        .HasColumnType("double")
                        .HasColumnName("land_width");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<double>("PlantSpacing")
                        .HasColumnType("double")
                        .HasColumnName("plant_spacing");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("project_id");

                    b.Property<double>("RowSpacing")
                        .HasColumnType("double")
                        .HasColumnName("row_spacing");

                    b.HasKey("Id");

                    b.ToTable("fields");
                });

            modelBuilder.Entity("SeedsBank.Server.Models.GalleryImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Caption")
                        .HasColumnType("longtext")
                        .HasColumnName("caption");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("file_path");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("uploaded_at");

                    b.HasKey("Id");

                    b.ToTable("gallery_images");
                });

            modelBuilder.Entity("SeedsBank.Server.Models.NewsPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("body");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("news_posts");
                });

            modelBuilder.Entity("SeedsBank.Server.Models.Project", b =>
                {
                    b.Property<string>("ProjectId")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("project_id");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_update");

                    b.Property<string>("PlantType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("plant_type");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("project_name");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("start_date");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("user_id");

                    b.HasKey("ProjectId");

                    b.ToTable("projects");
                });

            modelBuilder.Entity("SeedsBank.Server.Models.ProjectItem", b =>
                {
                    b.Property<string>("PlantId")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("plant_id");

                    b.Property<string>("FruitColor")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("fruit_color");

                    b.Property<string>("FruitWeight")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("fruit_weight");

                    b.Property<int>("Generation")
                        .HasColumnType("int")
                        .HasColumnName("generation");

                    b.Property<string>("Line")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("line");

                    b.Property<string>("PlantFatherId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("plant_father_id");

                    b.Property<string>("PlantMotherId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("plant_mother_id");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("project_id");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("project_name");

                    b.Property<string>("SeedColor")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("seed_color");

                    b.Property<string>("SeedWeight")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("seed_weight");

                    b.HasKey("PlantId");

                    b.ToTable("project_items");
                });

            modelBuilder.Entity("SeedsBank.Server.Models.SiteContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactAddress")
                        .HasColumnType("longtext")
                        .HasColumnName("contact_address");

                    b.Property<string>("ContactEmail")
                        .HasColumnType("longtext")
                        .HasColumnName("contact_email");

                    b.Property<string>("ContactPhone")
                        .HasColumnType("longtext")
                        .HasColumnName("contact_phone");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<string>("VideoUrl")
                        .HasColumnType("longtext")
                        .HasColumnName("video_url");

                    b.HasKey("Id");

                    b.ToTable("site_content");
                });

            modelBuilder.Entity("SeedsBank.Server.Models.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("userId");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("email");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("isAdmin");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password");

                    b.Property<string>("UserName")
                        .HasColumnType("longtext")
                        .HasColumnName("userName");

                    b.HasKey("UserId");

                    b.ToTable("users");
                });
#pragma warning restore 612, 618
        }
    }
}
